ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS sequence BIGINT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS actor TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS target TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS detail JSONB;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS detail_hash TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS prev_hash TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS entry_hash TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS anchored BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS anchor_tx_hash TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS redacted BOOLEAN NOT NULL DEFAULT FALSE;

CREATE UNIQUE INDEX IF NOT EXISTS idx_audit_logs_sequence ON audit_logs(sequence);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entry_hash ON audit_logs(entry_hash);
